### ISSUE TITLE
Syntax errors in Postbacks first rewrite example.

### ISSUE THREAD

**Issue by m8ram** [mdipierro/web2py-book#317]
The section on Postbacks contains the following code as a first alternative:
```
For example, here is one possible way to rewrite the first action:              
``                                                                              
def first():                                                                    
    form = FORM(INPUT(_name='visitor_name', requires=IS_NOT_EMPTY()),       
              INPUT(_type='submit'))                                            
    if form.process().accepted:                                                 
        session.visitor_name = form.vars.visitor_name                           
        redirect(URL('second'))                                                 
    return dict(form=form)                                                      
``:code
```

There are at least two issues with this code. first there is an additional closing bracket on the `form = ` line. This line should look like:
```
    form = FORM(INPUT(_name='visitor_name', requires=IS_NOT_EMPTY(),            
              INPUT(_type='submit'))                                            
```
But after this correction I get a syntax error I haven't been able to resolve yet. From the ticket that is created:
```
<type 'exceptions.SyntaxError'> non-keyword arg after keyword arg (default.py, line 36)
Version
web2py™ 	Version 2.14.3-stable+timestamp.2016.03.26.23.02.02
Python 	Python 2.7.10: /usr/bin/python (prefix: /usr)
Traceback

Traceback (most recent call last):
  File "/home/m8ram/workspace/realweb/web2py/gluon/restricted.py", line 226, in restricted
    ccode = compile2(code, layer)
  File "/home/m8ram/workspace/realweb/web2py/gluon/restricted.py", line 209, in compile2
    return compile(code.rstrip().replace('\r\n', '\n') + '\n', layer, 'exec')
  File "/home/m8ram/workspace/realweb/web2py/applications/myapp/controllers/default.py", line 36
    INPUT(_type='submit'))
SyntaxError: non-keyword arg after keyword arg

	
Traceback (most recent call last):
  File "/home/m8ram/workspace/realweb/web2py/gluon/restricted.py", line 226, in restricted
    ccode = compile2(code, layer)
  File "/home/m8ram/workspace/realweb/web2py/gluon/restricted.py", line 209, in compile2
    return compile(code.rstrip().replace('\r\n', '\n') + '\n', layer, 'exec')
  File "/home/m8ram/workspace/realweb/web2py/applications/myapp/controllers/default.py", line 36
    INPUT(_type='submit'))
SyntaxError: non-keyword arg after keyword arg

Error snapshot help

<type 'exceptions.SyntaxError'>(non-keyword arg after keyword arg (default.py, line 36)) 
```

The problem is with the ` INPUT(_type='submit')` because if I remove that the exception is not thrown and the page is displayed. But I fail to see what's wrong with that code.

p.s. If I copy the exception and code fro the ticket I get everything (including the code line numbers) except the code, I had to copy/paster that seperately.

**Comment by m8ram** [comment]
The example code in chapter 7 (07.markmin) has the same syntax and results in the same exception.
```
Here is the new controller:                                                     
``                                                                              
def display_form():                                                             
   form=FORM('Your name:', INPUT(_name='name'), INPUT(_type='submit'))          
   return dict(form=form)                                                       
``:code
```

**Comment by mdipierro** [comment]
I cannot reproduce any error with this code:

``
form=FORM('Your name:', INPUT(_name='name'), INPUT(_type='submit'))
``

**Comment by mdipierro** [comment]
was fixed.
